services:
  postgres:
    build:
      context: .
    image: local/postgres-postgis:16
    container_name: postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      EXTRA_USERS: ${EXTRA_USERS:-}
      EXTRA_DATABASES: ${EXTRA_DATABASES:-}
      EXTRA_EXTENSIONS: ${EXTRA_EXTENSIONS:-}

    volumes:
      - /srv/postgres/pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20

    networks:
      dokploy:
        aliases:
          - postgres

volumes:
  pgdata:

networks:
  dokploy:
    external: true
    name: dokploy-network
